spring:
  datasource:
    url: jdbc:mysql://192.168.37.99:3306/xw_test
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    content-type: text/html
    charset: UTF-8
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request

  velocity:
    resourceLoaderPath: classpath:/templates/
    prefix:
    suffix: .vm
    cache: false
    check-template-location: true
    content-type: text/html
    charset: UTF-8
    properties:
      input:
        encoding: UTF-8
      output:
        encoding: UTF-8